/*
	include/ClassiX/programs.h
*/

#ifndef _CLASSIX_PROGRAMS_H_
#define _CLASSIX_PROGRAMS_H_

#ifdef __cplusplus
	extern "C" {
#endif

#include <ClassiX/typedef.h>

enum {
	SRV_SUCCESS = 0,
	SRV_INVALID_PARAM,
	SRV_NOT_FOUND,
	SRV_MEMORY_ALLOC,
	SRV_READ_FAIL,
	SRV_INVALID_FORMAT
};

typedef enum {
	SYSCALL_EXIT_PROCESS = 0,
	SYSCALL_DEBUG_PRINT,
	SYSCALL_WAIT_EVENT,
	SYSCALL_WINDOW_CREATE,
	SYSCALL_WINDOW_DRAW_RECTANGLE,
	SYSCALL_WINDOW_DRAW_RECTANGLE_BY_CORNERS,
	SYSCALL_WINDOW_FILL_RECTANGLE,
	SYSCALL_WINDOW_FILL_RECTANGLE_BY_CORNERS,
	SYSCALL_WINDOW_DRAW_LINE,
	SYSCALL_WINDOW_DRAW_CIRCLE,
	SYSCALL_WINDOW_FILL_CIRCLE,
	SYSCALL_WINDOW_DRAW_ELLIPSE,
	SYSCALL_WINDOW_FILL_ELLIPSE,
	SYSCALL_WINDOW_DRAW_ASCII_STRING,
	SYSCALL_WINDOW_DRAW_UNICODE_STRING,
	SYSCALL_WINDOW_REFRESH,
} SYSCALL_NUMBER;

typedef enum {
	WINDOW_FONT_TERMINUS_12N = 0,
	WINDOW_FONT_TERMINUS_16N,
	WINDOW_FONT_TERMINUS_16B,
} WINDOW_FONT_ID;

int32_t program_exec(int32_t argc, char **argv);

#ifdef __cplusplus
	}
#endif

#endif